d <- read.csv(file = "household_power_consumption.txt", header = TRUE, na.strings = "?", sep = ";")
d$Date <- as.Date(d$Date, format = "%d/%m/%Y")
m <- subset(d, d$Date >= as.Date("2007-02-01") & d$Date <= as.Date("2007-02-02"))
remove(d)
m$Time <- as.POSIXlt(paste(m$Date, m$Time, sep = " "))
#sapply(m, function (x){sum(is.na(x))})
png(filename = "plot1.png")
hist(m$Global_active_power, col = "red", xlab = "Global Active Power (kilowatts)", main = "Global Active Power")
dev.off()