d <- read.csv(file = "household_power_consumption.txt", header = TRUE, na.strings = "?", sep = ";")
d$Date <- as.Date(d$Date, format = "%d/%m/%Y")
m <- subset(d, d$Date >= as.Date("2007-02-01") & d$Date <= as.Date("2007-02-02"))
remove(d)
m$Time <- as.POSIXlt(paste(m$Date, m$Time, sep = " "))
#sapply(m, function (x){sum(is.na(x))})
png(filename = "plot2.png")
plot(m$Time, m$Global_active_power, type = "l", xlab = " ", ylab = "Global Active Power (kilowatts)")
dev.off()